CREATE TABLE IF NOT EXISTS public.users (
    id UUID NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NULL,
    updated_at TIMESTAMP WITH TIME ZONE NULL,
    email VARCHAR(255) NOT NULL,
    profile_nickname VARCHAR(255) NULL,
    profile_image VARCHAR(255) NULL,
    is_deleted BOOLEAN NOT NULL,
    portal_connected BOOLEAN NULL,
    connected_at TIMESTAMP WITH TIME ZONE NULL,
    deleted_at TIMESTAMP WITH TIME ZONE NULL,
    last_synced_at TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_id UNIQUE (id)
);

CREATE TABLE IF NOT EXISTS public.departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE NULL,
    updated_at TIMESTAMP WITH TIME ZONE NULL,
    department_code VARCHAR(255) NULL,
    established_department_name VARCHAR(255) NULL,
    CONSTRAINT pk_departments PRIMARY KEY (id),
    CONSTRAINT uk_departments_department_code UNIQUE (department_code)
);

CREATE TABLE IF NOT EXISTS public.liberal_arts_area_codes (
    code INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NULL,
    updated_at TIMESTAMP WITH TIME ZONE NULL,
    is_active BOOLEAN NULL,
    area_name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NULL,
    CONSTRAINT pk_liberal_arts_area_codes PRIMARY KEY (code)
);

CREATE TABLE IF NOT EXISTS public.professor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    professor_code VARCHAR(255) NULL,
    professor_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NULL,
    department_id BIGINT NULL,
    CONSTRAINT pk_professor PRIMARY KEY (id),
    CONSTRAINT uk_professor_professor_name UNIQUE (professor_name)
);

CREATE TABLE IF NOT EXISTS public.courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE NULL,
    updated_at TIMESTAMP WITH TIME ZONE NULL,
    course_code VARCHAR(255) NOT NULL,
    course_name VARCHAR(255) NULL,
    deleted_at TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT pk_courses PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.course_offerings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE NULL,
    updated_at TIMESTAMP WITH TIME ZONE NULL,
    subject_establishment_semester INTEGER NULL,
    is_video_lecture BOOLEAN NULL,
    year INTEGER NOT NULL,
    semester INTEGER NOT NULL,
    host_department VARCHAR(255) NULL,
    class_section VARCHAR(255) NULL,
    schedule_summary VARCHAR(255) NULL,
    original_area_code INTEGER NULL,
    points INTEGER NULL,
    deleted_at TIMESTAMP WITH TIME ZONE NULL,
    evaluation_type_code VARCHAR(255) NULL,
    faculty_division_name VARCHAR(255) NULL,
    course_id BIGINT NOT NULL,
    department_id BIGINT NULL,
    professor_id BIGINT NULL,
    area_code INTEGER NULL,
    CONSTRAINT pk_course_offerings PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.students (
    student_id UUID NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NULL,
    updated_at TIMESTAMP WITH TIME ZONE NULL,
    student_code VARCHAR(255) NOT NULL,
    name VARCHAR(255) NULL,
    is_graduated BOOLEAN NULL,
    admission_type VARCHAR(255) NULL,
    target_gpa DOUBLE PRECISION NULL,
    reconnection_required BOOLEAN NOT NULL,
    admission_year INTEGER NOT NULL,
    semester_enrolled INTEGER NULL,
    is_transfer_student BOOLEAN NULL,
    status VARCHAR(255) NULL,
    grade_level INTEGER NULL,
    completed_semesters INTEGER NULL,
    department_id BIGINT NOT NULL,
    major_id BIGINT NULL,
    secondary_major_id BIGINT NULL,
    user_id UUID NOT NULL,
    CONSTRAINT pk_students PRIMARY KEY (student_id),
    CONSTRAINT uk_students_student_code UNIQUE (student_code),
    CONSTRAINT uk_students_user_id UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.social_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    provider VARCHAR(255) NOT NULL,
    social_id VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    user_id UUID NOT NULL,
    CONSTRAINT pk_social_accounts PRIMARY KEY (id),
    CONSTRAINT uk_provider_social_id UNIQUE (provider, social_id)
);

CREATE TABLE IF NOT EXISTS public.refresh_token (
    user_id VARCHAR(255) NOT NULL,
    token VARCHAR(255) NOT NULL,
    expiry TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_refresh_token PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.student_academic_records (
    id UUID NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NULL,
    updated_at TIMESTAMP WITH TIME ZONE NULL,
    attempted_credits_gpa NUMERIC(38, 2) NULL,
    percentile NUMERIC(38, 2) NULL,
    cumulative_gpa NUMERIC(38, 2) NULL,
    total_attempted_credits INTEGER NULL,
    total_earned_credits INTEGER NULL,
    student_id UUID NOT NULL,
    CONSTRAINT pk_student_academic_records PRIMARY KEY (id),
    CONSTRAINT uk_student_academic_records_student_id UNIQUE (student_id)
);

CREATE TABLE IF NOT EXISTS public.semester_academic_records (
    id UUID NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NULL,
    updated_at TIMESTAMP WITH TIME ZONE NULL,
    semester INTEGER NOT NULL,
    year INTEGER NULL,
    total_students INTEGER NULL,
    class_rank INTEGER NULL,
    attempted_credits_gpa NUMERIC(38, 2) NULL,
    semester_percentile NUMERIC(38, 2) NULL,
    semester_gpa NUMERIC(38, 2) NULL,
    attempted_credits INTEGER NULL,
    earned_credits INTEGER NULL,
    student_id UUID NOT NULL,
    CONSTRAINT pk_semester_academic_records PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.student_courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    grade VARCHAR(255) NULL,
    points INTEGER NULL,
    is_retake BOOLEAN NULL,
    original_score INTEGER NULL,
    created_at TIMESTAMP WITH TIME ZONE NULL,
    is_retake_deleted BOOLEAN NOT NULL,
    offering_id BIGINT NOT NULL,
    student_id UUID NOT NULL,
    CONSTRAINT pk_student_courses PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.department_area_requirements (
    id UUID NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NULL,
    updated_at TIMESTAMP WITH TIME ZONE NULL,
    total_elective_courses INTEGER NULL,
    required_elective_courses INTEGER NULL,
    admission_year INTEGER NOT NULL,
    required_credits INTEGER NOT NULL,
    description VARCHAR(255) NULL,
    area_type VARCHAR(255) NOT NULL,
    department_id BIGINT NOT NULL,
    CONSTRAINT pk_department_area_requirements PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.dual_major_requirements (
    id UUID NOT NULL,
    major_role VARCHAR(255) NOT NULL,
    admission_year INTEGER NOT NULL,
    area_type VARCHAR(255) NOT NULL,
    required_credits INTEGER NOT NULL,
    department_id BIGINT NOT NULL,
    CONSTRAINT pk_dual_major_requirements PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.graduation_requirements (
    id UUID NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NULL,
    updated_at TIMESTAMP WITH TIME ZONE NULL,
    total_credits INTEGER NOT NULL,
    admission_year INTEGER NULL,
    minimum_gpa NUMERIC(38, 2) NULL,
    department_id BIGINT NULL,
    CONSTRAINT pk_graduation_requirements PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.student_graduation_progress (
    id UUID NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NULL,
    updated_at TIMESTAMP WITH TIME ZONE NULL,
    elective_courses_fulfilled BOOLEAN NULL,
    credits_fulfilled BOOLEAN NULL,
    language_cert_fulfilled BOOLEAN NULL,
    gpa_fulfilled BOOLEAN NULL,
    checked_at TIMESTAMP WITH TIME ZONE NULL,
    area_requirements_fulfilled BOOLEAN NULL,
    graduation_status VARCHAR(255) NULL,
    student_id UUID NULL,
    CONSTRAINT pk_student_graduation_progress PRIMARY KEY (id),
    CONSTRAINT uk_student_graduation_progress_student_id UNIQUE (student_id)
);

CREATE TABLE IF NOT EXISTS public.scrape_jobs (
    job_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NULL,
    updated_at TIMESTAMP WITH TIME ZONE NULL,
    user_id UUID NOT NULL,
    portal_type VARCHAR(255) NOT NULL,
    operation_type VARCHAR(255) NOT NULL,
    idempotency_key VARCHAR(255) NOT NULL,
    request_fingerprint VARCHAR(64) NOT NULL,
    status VARCHAR(255) NOT NULL,
    request_payload_json TEXT NOT NULL,
    result_payload_json TEXT NULL,
    result_s3_key VARCHAR(255) NULL,
    result_checksum VARCHAR(255) NULL,
    callback_attempt INTEGER NULL,
    callback_received_at TIMESTAMP WITH TIME ZONE NULL,
    callback_metadata_json TEXT NULL,
    error_code VARCHAR(255) NULL,
    error_message TEXT NULL,
    retryable BOOLEAN NULL,
    finished_at TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT pk_scrape_jobs PRIMARY KEY (job_id),
    CONSTRAINT uk_scrape_jobs_user_idempotency UNIQUE (user_id, idempotency_key)
);

CREATE TABLE IF NOT EXISTS public.scrape_job_outbox (
    outbox_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NULL,
    updated_at TIMESTAMP WITH TIME ZONE NULL,
    job_id VARCHAR(255) NOT NULL,
    payload_json TEXT NOT NULL,
    status VARCHAR(255) NOT NULL,
    attempt_count INTEGER NOT NULL,
    next_attempt_at TIMESTAMP WITH TIME ZONE NULL,
    last_attempt_at TIMESTAMP WITH TIME ZONE NULL,
    sent_at TIMESTAMP WITH TIME ZONE NULL,
    queue_message_id VARCHAR(255) NULL,
    last_error TEXT NULL,
    CONSTRAINT pk_scrape_job_outbox PRIMARY KEY (outbox_id),
    CONSTRAINT uk_scrape_job_outbox_job_id UNIQUE (job_id)
);

ALTER TABLE public.professor
    ADD CONSTRAINT fk_professor_department_id
    FOREIGN KEY (department_id) REFERENCES public.departments (id);

ALTER TABLE public.course_offerings
    ADD CONSTRAINT fk_course_offerings_course_id
    FOREIGN KEY (course_id) REFERENCES public.courses (id);

ALTER TABLE public.course_offerings
    ADD CONSTRAINT fk_course_offerings_department_id
    FOREIGN KEY (department_id) REFERENCES public.departments (id);

ALTER TABLE public.course_offerings
    ADD CONSTRAINT fk_course_offerings_professor_id
    FOREIGN KEY (professor_id) REFERENCES public.professor (id);

ALTER TABLE public.course_offerings
    ADD CONSTRAINT fk_course_offerings_area_code
    FOREIGN KEY (area_code) REFERENCES public.liberal_arts_area_codes (code);

ALTER TABLE public.students
    ADD CONSTRAINT fk_students_department_id
    FOREIGN KEY (department_id) REFERENCES public.departments (id);

ALTER TABLE public.students
    ADD CONSTRAINT fk_students_major_id
    FOREIGN KEY (major_id) REFERENCES public.departments (id);

ALTER TABLE public.students
    ADD CONSTRAINT fk_students_secondary_major_id
    FOREIGN KEY (secondary_major_id) REFERENCES public.departments (id);

ALTER TABLE public.students
    ADD CONSTRAINT fk_students_user_id
    FOREIGN KEY (user_id) REFERENCES public.users (id);

ALTER TABLE public.social_accounts
    ADD CONSTRAINT fk_social_accounts_user_id
    FOREIGN KEY (user_id) REFERENCES public.users (id);

ALTER TABLE public.student_academic_records
    ADD CONSTRAINT fk_student_academic_records_student_id
    FOREIGN KEY (student_id) REFERENCES public.students (student_id);

ALTER TABLE public.semester_academic_records
    ADD CONSTRAINT fk_semester_academic_records_student_id
    FOREIGN KEY (student_id) REFERENCES public.students (student_id);

ALTER TABLE public.student_courses
    ADD CONSTRAINT fk_student_courses_offering_id
    FOREIGN KEY (offering_id) REFERENCES public.course_offerings (id);

ALTER TABLE public.student_courses
    ADD CONSTRAINT fk_student_courses_student_id
    FOREIGN KEY (student_id) REFERENCES public.students (student_id);

ALTER TABLE public.department_area_requirements
    ADD CONSTRAINT fk_department_area_requirements_department_id
    FOREIGN KEY (department_id) REFERENCES public.departments (id);

ALTER TABLE public.dual_major_requirements
    ADD CONSTRAINT fk_dual_major_requirements_department_id
    FOREIGN KEY (department_id) REFERENCES public.departments (id);

ALTER TABLE public.graduation_requirements
    ADD CONSTRAINT fk_graduation_requirements_department_id
    FOREIGN KEY (department_id) REFERENCES public.departments (id);

ALTER TABLE public.student_graduation_progress
    ADD CONSTRAINT fk_student_graduation_progress_student_id
    FOREIGN KEY (student_id) REFERENCES public.students (student_id);

ALTER TABLE public.scrape_job_outbox
    ADD CONSTRAINT fk_scrape_job_outbox_job_id
    FOREIGN KEY (job_id) REFERENCES public.scrape_jobs (job_id);

CREATE INDEX IF NOT EXISTS idx_student_year_semester
    ON public.semester_academic_records (student_id, year, semester);

CREATE INDEX IF NOT EXISTS idx_scrape_job_outbox_status_next_attempt_at
    ON public.scrape_job_outbox (status, next_attempt_at);

CREATE INDEX IF NOT EXISTS idx_scrape_job_outbox_status_sent_at
    ON public.scrape_job_outbox (status, sent_at);
